name: Test Log Output
env:
  REPO_NAME: ${{ github.event.repository.name }}
on: [push]
jobs:
  print-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Wypisz powitanie
        run: echo "Witaj w GitHub Actions!"
      - name: Test echo
        run: echo "sprawdzamy - $REPO_NAME"
        # run: echo "$REPO_NAME"  # Działa wszędzie
        # run: echo "Branch: ${{ github.ref }}"
        # run: echo "Repo: ${{ github.event.repository.name }}"
        # run: echo "Job status: ${{ job.status }}"
