name: Test Log Output
on: [push]
jobs:
  print-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Wypisz powitanie
        run: echo "Witaj w GitHub Actions!"
      - name: Test echo
        run: echo "sprawdzamy"
        # run: echo "Branch: ${{ github.ref }}"
        run: echo "Repo: ${{ github.event.repository.name }}"
        # run: echo "Job status: ${{ job.status }}"
